name: cleanup
on:
  workflow_dispatch:
  #push:
    #branches:
      #- main
jobs:
  destroy:
    name: destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Stop and remove container
        run: |
          docker ps -q --filter "name=game" | grep -q . && docker stop game || echo "Container 'game' not running."
          docker ps -aq --filter "name=game" | grep -q . && docker rm game || echo "Container 'game' not found."
      - name: Update kubeconfig
        run: aws eks --region eu-west-2 update-kubeconfig --name EKS_CLOUD
      - name: Deploy to kubernetes
        run: kubectl delete -f deployment-service.yml
